### ISSUE TITLE
Can't make a successful request to external API

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/project-2#1]
Request to external API is working in Postman, but I haven't been able to have it work in sublime.  I've consulted the following resources to no avail: 

https://www.npmjs.com/package/request#http-authentication
http://passportjs.org/docs/basic-digest

Any classmate I have asked didn't know how to assist in my specific case.

**Comment by ZebGirouard** [comment]
Jacy and I pushed through this error, only to find a 500 error behind it.  We'll take a look again tomorrow, but I have no idea why this error is popping up.

**Comment by ZebGirouard** [comment]
Command line for the win!
