### ISSUE TITLE
heroku trials

### ISSUE THREAD

**Issue by robertschank** [den-materials/project-2#14]
heroku logs has a lot to say. It doesn't like that I'm gitignoring my env.js file, so it can't access my api key. Troy.
http://stackoverflow.com/questions/35735663/how-to-add-api-keys-to-heroku

https://github.com/SF-WDI-LABS/shared_modules/blob/master/how-to/heroku-mean-stack-deploy.md

**Comment by ZebGirouard** [comment]
Looks like this is all set now.
