### ISSUE TITLE
Heroku logs issues

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/project-2#16]
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at server.js

despite providing the aforementioned info, still receiving error. Asked bobby and troy. 

http://stackoverflow.com/questions/28839532/node-js-session-error-express-session-deprecated/34744627

**Comment by ZebGirouard** [comment]
Actually mongo issue, looks like you're off to a good start on it.
