### ISSUE TITLE
Can't override heroku app from server / local folder

### ISSUE THREAD

**Issue by luluwelborn** [den-materials/project-2#27]
I deleted the old app in heroku that was having issues, created a new one in terminal, and when I enter "heroku addons:create mongolab" it looks for the deleted app:
Creating mongolab on ⬢ rocky-plains-41531... !
 ▸    Couldn't find that app.

I can't find a source with instruction to override the deleted app with the new one. Please advise. Thanks!

**Comment by ZebGirouard** [comment]
Talked to Lauren, she's going to try moving her folder, cloning latest down from GitHub, and starting fresh with Heroku.  Seems like a solid approach.
