### ISSUE TITLE
Async and loops

### ISSUE THREAD

**Issue by CRCastells** [den-materials/project-2#34]
In one of my controllers I am trying to replace mongo reference data with the real object before passing that onto EJS and displaying that on my profile page within my app. I am having trouble dealing with the asynchronous calls with mongoose while iterating through the array. I would like to incorporate Promises into the code, but I still notice that the loop continues before the promise resolves. How do I get this to either run more like a sync function, or wait to deal with the resolving promise after the fact and still use the data to template into EJS. I usually run into the error about unable to set headers after response is sent.

<pre> 
function getProfile(req, res) {
	let user = req.user;
	let revs = [];
	let visited = [];
	//grab all restaurants the user has been to
	db.Restaurant.find({_id: {$in: user.visited}} , function (err, restaurants) {
		visited = restaurants;
		//grab all the reviews for each restaurant
		visited.forEach(r => {
			//find all reviews for each restaurant
			db.Review.find({_id: {$in: r.reviews}}, function(err, reviews){
				//add the real object into the restaurant object
				r.reviews = reviews;
				// add the restaurant object with populated reviews into visited array
				visited.push(r);
			});
		});
		//find all reviews a user has made
		db.Review.find({_id: {$in: user.reviews}},function(err, reviews){
			//for each review
			reviews.forEach(r => {
				//grab all restaurants that the reviews the user made match
				db.Restaurant.findById(r.restaurant, function(err, rest) {
					//replace review's restaurant id with object
					r.restaurant = rest;
					//add the review to the reviews array
					revs.push(r);
				});
			});
			//render the data
			res.render('profile', {user, reviews:revs, visited});
		});
	});
	
}
</pre>

**Comment by ZebGirouard** [comment]
All set now!
