### ISSUE TITLE
Bootstrap not implementing properly (working in some places, not others)

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/project-2#4]
http://translationexchange.com/blog/getting-started-with-node-js-express-ejs-bootstrap-and-tml/
http://getbootstrap.com/getting-started/#download-cdn

Asked some people to no avail

**Comment by ZebGirouard** [comment]
We made a little progress but keeping the issue open for now

**Comment by ZebGirouard** [comment]
Woo hoo, Jacy got it!
