### ISSUE TITLE
3rd party API Access with Request

### ISSUE THREAD

**Issue by robertschank** [den-materials/project-2#6]
I'm not sure where the best place is to manipulate my 3rd party data.  I figure I will strip down the request.body to an array of just what I need, then send that back in my res.send.  Right now all this is in a controller.

https://stackoverflow.com/questions/43267469/how-to-connect-front-end-and-back-end-with-node-from-rest-api
https://blog.lovemily.me/dispatch-api-requests-with-nodejs-request-module/

**Comment by ZebGirouard** [comment]
Looks good to me.
